### PR TITLE
Optional registration passwords and catalog-request cleanup

### PR DESCRIPTION
**Pull request by wking**
I found this branch locally, and we may need some of it for @davidmcatee-azure's getting-started reroll.

### CODE REVIEW

**Comment by davidmcatee-azure** [comment]
Don't we need [`catalog` _and_ `sale_magazine`](https://github.com/azurestandard/beehive/blob/master/apps/api/views/registration.py#L151-L152)?

The corresponding options on the existing Get Started UI are still on the new UI:

image

**Comment by wking** [comment]
On Thu, Oct 13, 2016 at 03:18:33PM -0700, David McAtee wrote:
> Don't we need `catalog` _and_ `sale_magazine`…

Maybe the commit message subject needs work, but with this branch we
*do* have both ‘catalog’ [1] and ‘sale-magazine’ [2] (with hyphenation
to match the rest of the API).

[1]: https://github.com/azurestandard/api-spec/pull/164/files#diff-380fafdca01526afaf5cbc26fb2f0983R6574
[2]: https://github.com/azurestandard/api-spec/pull/164/files#diff-380fafdca01526afaf5cbc26fb2f0983R6774

**Comment by wking** [comment]
Ah, perhaps the confusion was because I'm [only supporting `sale-magazine` in `updatePersonUserPassword`][1]?

[1]: https://github.com/azurestandard/api-spec/pull/164/files#diff-380fafdca01526afaf5cbc26fb2f0983R6794

**Comment by davidmcatee-azure** [comment]
Sorry, clearly I need to look at this more closely.

**Comment by wking** [comment]
I removed the WIP tag now that [we have clarity on how this will work][1].  This is ready for review now.

[1]: https://github.com/azurestandard/beehive/issues/1170#issuecomment-259744799

**Pull request merged**
