### PR TITLE
public.json: Add sale model

### PR DESCRIPTION
**Pull request by wking**
With the coming price restructuring, we're going to be applying sales on the frontend.  This commit lets us do that independent of the other price restructuring.

### CODE REVIEW

**Comment by wking** [comment]
I've pushed 5da9edee0 → 907b23b90 going from cent rounding to nickle rounding so we can address the rest of this PR without waiting on azurestandard/beehive#2875.

**Comment by wking** [comment]
I've pushed 907b23b → f208df1 adding sale endpoints (907b23b just had inlined sale models).  This will allow us to use the public sale model for the internal pricing UI as well.

**Comment by wking** [comment]
I've pushed f208df1 → 476ca05 adding some notes about handling multiple active sales (only the largest active sale matters).

**Comment by wking** [comment]
I've pushed 476ca05 → bcb9755, rebasing onto master and restoring the cent-rounding (previously removed [here][1]), now that it sounds like we're going ahead with the nickle-round drop.

Also ping @caseybessette on this PR as a whole, since you've been working on the phase-III pricing that this is a part of.

[1]: https://github.com/azurestandard/api-spec/pull/204#issuecomment-309918507

**Comment by caseybessette** [comment]
We have decided to take a different implementation route.

**Pull request closed without merging**
